Modify TrajOptPlanner to allow a user to add custom terms to the trajectory optimization
KavrakiLab/robowflex pull request #233
Opened 2021-07-28 22:54 UTC by carlosquinterop

- It is now possible to inherit from the TrajOptPlanner class and override a plan() method. By doing this, the user can add custom terms (costs or constraints) into the trajectory optimization problem.
- The joint velocity cost is now incorporated in the new method addVelocityCost(). It used to be added in ProblemConstructionInfo() but since now the user can create custom problems, it is more convenient that everything is separated.
- A new script that shows how a user can create a custom trajopt planner for a UR5 robot and use it to add cartesian constraints for the end-effector for motion planning. The result is shown in the figure below:

![custom_trajopt_planner](https://user-images.githubusercontent.com/12850445/127406296-da01bbfc-d286-4318-b0da-f588ad227e9e.png)

2021-07-29 02:29 UTC, zkingston requested changes
Some small nits. We should also add a trajopt docker to the CI to check compilation + maybe a small test script.

2021-07-29 02:29 UTC, zkingston commented on robowflex_tesseract/src/trajopt_planner.cpp
> +    RBX_ERROR("You need to implement virtual method TrajOptPlanner::plan() in your derived class");
probably better to throw an exception here rather than just a print

2021-07-29 02:29 UTC, zkingston commented on robowflex_tesseract/scripts/ur5_custom_planning.cpp
> +namespace robowflex
the custom class doesn't need to be in the robowflex namespace, you can just have it in the global

2021-08-07 23:16 UTC, carlosquinterop commented
> Some small nits. We should also add a trajopt docker to the CI to check compilation + maybe a small test script.

I've addressed the specific comments and also updated the README file accordingly. Regarding the docker to the CI, I'll go ahead and open an issue with this so we can address it in a different PR

2021-08-08 18:29 UTC, zkingston approved these changes

2021-08-08 18:47 UTC, merged